#ivy cached data file for none#aopalliance;
#Tue Apr 07 07:30:35 EDT 2026
artifact.resolver=cvslib
artifact\:aopalliance\#jar\#jar\#-1461909707.exists=true
artifact\:aopalliance\#jar\#jar\#-1461909707.is-local=true
artifact\:aopalliance\#jar\#jar\#-1461909707.location=/Users/nick/Documents/hermes-wireshare/main/lib/jars/aopalliance.jar
artifact\:aopalliance\#jar\#jar\#-1461909707.original=artifact\:aopalliance\#jar\#jar\#-1461909707
resolver=cvslib
