#ivy cached data file for org.limewire#player;working@local
#Tue Apr 07 07:30:34 EDT 2026
artifact\:ivy\#ivy.original\#xml\#1157668796.exists=true
artifact\:ivy\#ivy.original\#xml\#1157668796.is-local=true
artifact\:ivy\#ivy.original\#xml\#1157668796.location=/Users/nick/Documents/hermes-wireshare/main/.ivy2/local/org.limewire/player/ivys/ivy.xml
artifact\:ivy\#ivy.original\#xml\#1157668796.original=artifact\:ivy\#ivy.original\#xml\#1157668796
