#ivy cached data file for org.limewire#common;working@local
#Tue Apr 07 07:30:32 EDT 2026
artifact\:ivy\#ivy.original\#xml\#1292520960.exists=true
artifact\:ivy\#ivy.original\#xml\#1292520960.is-local=true
artifact\:ivy\#ivy.original\#xml\#1292520960.location=/Users/nick/Documents/hermes-wireshare/main/.ivy2/local/org.limewire/common/ivys/ivy.xml
artifact\:ivy\#ivy.original\#xml\#1292520960.original=artifact\:ivy\#ivy.original\#xml\#1292520960
