#ivy cached data file for none#swingx;1.0
#Tue Apr 07 07:30:35 EDT 2026
artifact.resolver=cvslib
artifact\:swingx\#jar\#jar\#1858188287.exists=true
artifact\:swingx\#jar\#jar\#1858188287.is-local=true
artifact\:swingx\#jar\#jar\#1858188287.location=/Users/nick/Documents/hermes-wireshare/main/lib/jars/swingx-1.0.jar
artifact\:swingx\#jar\#jar\#1858188287.original=artifact\:swingx\#jar\#jar\#1858188287
resolver=cvslib
