#ivy cached data file for none#foxtrot-core;3.0
#Tue Apr 07 07:30:35 EDT 2026
artifact.resolver=cvslib
artifact\:foxtrot-core\#jar\#jar\#-971100231.exists=true
artifact\:foxtrot-core\#jar\#jar\#-971100231.is-local=true
artifact\:foxtrot-core\#jar\#jar\#-971100231.location=/Users/nick/Documents/hermes-wireshare/main/lib/jars/foxtrot-core-3.0.jar
artifact\:foxtrot-core\#jar\#jar\#-971100231.original=artifact\:foxtrot-core\#jar\#jar\#-971100231
resolver=cvslib
