#ivy cached data file for none#jcip-annotations;
#Tue Apr 07 07:30:35 EDT 2026
artifact.resolver=cvslib
artifact\:jcip-annotations\#jar\#jar\#-1464541105.exists=true
artifact\:jcip-annotations\#jar\#jar\#-1464541105.is-local=true
artifact\:jcip-annotations\#jar\#jar\#-1464541105.location=/Users/nick/Documents/hermes-wireshare/main/lib/jars/jcip-annotations.jar
artifact\:jcip-annotations\#jar\#jar\#-1464541105.original=artifact\:jcip-annotations\#jar\#jar\#-1464541105
resolver=cvslib
