#ivy cached data file for none#osx/asm;3.1
#Tue Apr 07 07:30:35 EDT 2026
artifact.resolver=cvslib
artifact\:osx/asm\#jar\#jar\#1974323576.exists=true
artifact\:osx/asm\#jar\#jar\#1974323576.is-local=true
artifact\:osx/asm\#jar\#jar\#1974323576.location=/Users/nick/Documents/hermes-wireshare/main/lib/jars/osx/asm-3.1.jar
artifact\:osx/asm\#jar\#jar\#1974323576.original=artifact\:osx/asm\#jar\#jar\#1974323576
resolver=cvslib
