#ivy cached data file for none#windows/iTunes;0.0.1
#Tue Apr 07 07:30:35 EDT 2026
artifact.resolver=cvslib
artifact\:windows/iTunes\#jar\#jar\#-742342203.exists=true
artifact\:windows/iTunes\#jar\#jar\#-742342203.is-local=true
artifact\:windows/iTunes\#jar\#jar\#-742342203.location=/Users/nick/Documents/hermes-wireshare/main/lib/jars/windows/iTunes-0.0.1.jar
artifact\:windows/iTunes\#jar\#jar\#-742342203.original=artifact\:windows/iTunes\#jar\#jar\#-742342203
resolver=cvslib
