#ivy cached data file for none#osx/slf4j-api;1.5.8
#Tue Apr 07 07:30:35 EDT 2026
artifact.resolver=cvslib
artifact\:osx/slf4j-api\#jar\#jar\#-1171805501.exists=true
artifact\:osx/slf4j-api\#jar\#jar\#-1171805501.is-local=true
artifact\:osx/slf4j-api\#jar\#jar\#-1171805501.location=/Users/nick/Documents/hermes-wireshare/main/lib/jars/osx/slf4j-api-1.5.8.jar
artifact\:osx/slf4j-api\#jar\#jar\#-1171805501.original=artifact\:osx/slf4j-api\#jar\#jar\#-1171805501
resolver=cvslib
