#ivy cached data file for none#commons-logging;
#Tue Apr 07 07:30:35 EDT 2026
artifact.resolver=cvslib
artifact\:commons-logging\#jar\#jar\#1315341960.exists=true
artifact\:commons-logging\#jar\#jar\#1315341960.is-local=true
artifact\:commons-logging\#jar\#jar\#1315341960.location=/Users/nick/Documents/hermes-wireshare/main/lib/jars/commons-logging.jar
artifact\:commons-logging\#jar\#jar\#1315341960.original=artifact\:commons-logging\#jar\#jar\#1315341960
resolver=cvslib
