#ivy cached data file for none#mozswing;
#Tue Apr 07 07:30:35 EDT 2026
artifact.resolver=cvslib
artifact\:mozswing\#jar\#jar\#215242892.exists=true
artifact\:mozswing\#jar\#jar\#215242892.is-local=true
artifact\:mozswing\#jar\#jar\#215242892.location=/Users/nick/Documents/hermes-wireshare/main/lib/jars/mozswing.jar
artifact\:mozswing\#jar\#jar\#215242892.original=artifact\:mozswing\#jar\#jar\#215242892
resolver=cvslib
