#ivy cached data file for none#jorbis;
#Tue Apr 07 07:30:35 EDT 2026
artifact.resolver=cvslib
artifact\:jorbis\#jar\#jar\#-413460921.exists=true
artifact\:jorbis\#jar\#jar\#-413460921.is-local=true
artifact\:jorbis\#jar\#jar\#-413460921.location=/Users/nick/Documents/hermes-wireshare/main/lib/jars/jorbis.jar
artifact\:jorbis\#jar\#jar\#-413460921.original=artifact\:jorbis\#jar\#jar\#-413460921
resolver=cvslib
