#ivy cached data file for none#TimingFramework;1.0
#Tue Apr 07 07:30:35 EDT 2026
artifact.resolver=cvslib
artifact\:TimingFramework\#jar\#jar\#633905933.exists=true
artifact\:TimingFramework\#jar\#jar\#633905933.is-local=true
artifact\:TimingFramework\#jar\#jar\#633905933.location=/Users/nick/Documents/hermes-wireshare/main/lib/jars/TimingFramework-1.0.jar
artifact\:TimingFramework\#jar\#jar\#633905933.original=artifact\:TimingFramework\#jar\#jar\#633905933
resolver=cvslib
