#ivy cached data file for org.limewire#http;working@local
#Tue Apr 07 07:30:32 EDT 2026
artifact\:ivy\#ivy.original\#xml\#1089276050.exists=true
artifact\:ivy\#ivy.original\#xml\#1089276050.is-local=true
artifact\:ivy\#ivy.original\#xml\#1089276050.location=/Users/nick/Documents/hermes-wireshare/main/.ivy2/local/org.limewire/http/ivys/ivy.xml
artifact\:ivy\#ivy.original\#xml\#1089276050.original=artifact\:ivy\#ivy.original\#xml\#1089276050
