#org.limewire#collection;working@pandora.local resolved revisions
#Tue Apr 07 07:30:32 EDT 2026
+organisation\:\#@\#\:+none\:\#@\#\:+branch\:\#@\#\:+@\#\:NULL\:\#@\:\#@\#\:+module\:\#@\#\:+commons-logging\:\#@\#\:+revision\:\#@\#\:+\:\#@\#\:=\ release  null
+organisation\:\#@\#\:+none\:\#@\#\:+branch\:\#@\#\:+@\#\:NULL\:\#@\:\#@\#\:+module\:\#@\#\:+glazedlists\:\#@\#\:+revision\:\#@\#\:+snapshot20090628_java15\:\#@\#\:=snapshot20090628_java15 release snapshot20090628_java15 null
+organisation\:\#@\#\:+org.limewire\:\#@\#\:+branch\:\#@\#\:+@\#\:NULL\:\#@\:\#@\#\:+module\:\#@\#\:+common\:\#@\#\:+revision\:\#@\#\:+latest.integration\:\#@\#\:=20260407073032 integration 20260407073032 null
