#org.limewire#common;working@pandora.local resolved revisions
#Tue Apr 07 07:30:31 EDT 2026
+organisation\:\#@\#\:+none\:\#@\#\:+branch\:\#@\#\:+@\#\:NULL\:\#@\:\#@\#\:+module\:\#@\#\:+aopalliance\:\#@\#\:+revision\:\#@\#\:+\:\#@\#\:=\ release  null
+organisation\:\#@\#\:+none\:\#@\#\:+branch\:\#@\#\:+@\#\:NULL\:\#@\:\#@\#\:+module\:\#@\#\:+commons-logging\:\#@\#\:+revision\:\#@\#\:+\:\#@\#\:=\ release  null
+organisation\:\#@\#\:+none\:\#@\#\:+branch\:\#@\#\:+@\#\:NULL\:\#@\:\#@\#\:+module\:\#@\#\:+guice\:\#@\#\:+revision\:\#@\#\:+2.0-snapshot20090814\:\#@\#\:=2.0-snapshot20090814 release 2.0-snapshot20090814 null
+organisation\:\#@\#\:+none\:\#@\#\:+branch\:\#@\#\:+@\#\:NULL\:\#@\:\#@\#\:+module\:\#@\#\:+icu4j\:\#@\#\:+revision\:\#@\#\:+\:\#@\#\:=\ release  null
