#ivy cached data file for none#onion-fec;
#Tue Apr 07 07:30:35 EDT 2026
artifact.resolver=cvslib
artifact\:onion-fec\#jar\#jar\#2050337530.exists=true
artifact\:onion-fec\#jar\#jar\#2050337530.is-local=true
artifact\:onion-fec\#jar\#jar\#2050337530.location=/Users/nick/Documents/hermes-wireshare/main/lib/jars/onion-fec.jar
artifact\:onion-fec\#jar\#jar\#2050337530.original=artifact\:onion-fec\#jar\#jar\#2050337530
resolver=cvslib
