#ivy cached data file for none#jxlayer;4.0
#Tue Apr 07 07:30:35 EDT 2026
artifact.resolver=cvslib
artifact\:jxlayer\#jar\#jar\#-1141749967.exists=true
artifact\:jxlayer\#jar\#jar\#-1141749967.is-local=true
artifact\:jxlayer\#jar\#jar\#-1141749967.location=/Users/nick/Documents/hermes-wireshare/main/lib/jars/jxlayer-4.0.jar
artifact\:jxlayer\#jar\#jar\#-1141749967.original=artifact\:jxlayer\#jar\#jar\#-1141749967
resolver=cvslib
