#ivy cached data file for none#compile/AppleJavaExtensions;
#Tue Apr 07 07:30:35 EDT 2026
artifact.resolver=cvslib
artifact\:compile/AppleJavaExtensions\#jar\#jar\#1057665334.exists=true
artifact\:compile/AppleJavaExtensions\#jar\#jar\#1057665334.is-local=true
artifact\:compile/AppleJavaExtensions\#jar\#jar\#1057665334.location=/Users/nick/Documents/hermes-wireshare/main/lib/jars/compile/AppleJavaExtensions.jar
artifact\:compile/AppleJavaExtensions\#jar\#jar\#1057665334.original=artifact\:compile/AppleJavaExtensions\#jar\#jar\#1057665334
resolver=cvslib
