#!/bin/bash
#
# resolve symlinks
#####################

PRG=$0

while [ -h "$PRG" ]; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '^.*-> \(.*\)$' 2>/dev/null`
    if expr "$link" : '^/' 2> /dev/null >/dev/null; then
        PRG="$link"
    else
        PRG="`dirname "$PRG"`/$link"
    fi
done

#
# Set default variables and settings
#######################################

PROGDIR=`dirname "$PRG"`
cd $(eval echo "$PROGDIR/../..")
APP_PACKAGE="$PWD"
JAVAROOT="$APP_PACKAGE/Contents/Resources/Java"
USER_HOME=$HOME
cd "$USER_HOME"


#
# read Info.plist and extract JVM options
############################################

# set path to Info.plist in bundle
InfoPlistFile="$APP_PACKAGE/Contents/Info.plist"

# read the program name from CFBundleName
CFBundleName=`/usr/libexec/PlistBuddy -c "print :CFBundleName" ${InfoPlistFile}`

# read the icon file name
CFBundleIconFile=`/usr/libexec/PlistBuddy -c "print :CFBundleIconFile" ${InfoPlistFile}`

# read the preferred architecture
JVMArchs=`/usr/libexec/PlistBuddy -c "print :LSArchitecturePriority:0" ${InfoPlistFile}`

# read java min version
JVMVersion=`/usr/libexec/PlistBuddy -c "print :JavaVM:JVMVersion" ${InfoPlistFile} 2> /dev/null`

# read classpath
JVMClasspath=`/usr/libexec/PlistBuddy -c "print :JavaVM:ClassPath" ${InfoPlistFile} 2> /dev/null | tr '\n' ' ' | sed -E 's/Array \{ *(.*) *\}/\1/g' | sed 's/  */:/g' | xargs`
JVMClasspath="${JVMClasspath/%:/}"

# read the WorkingDirectory name
WorkingDirectory=$(eval echo `/usr/libexec/PlistBuddy -c "print :JavaVM:WorkingDirectory" ${InfoPlistFile} 2> /dev/null`)
cd $WorkingDirectory

# read the MainClass name
JVMMainClass=`/usr/libexec/PlistBuddy -c "print :JavaVM:MainClass" ${InfoPlistFile} 2> /dev/null`
	
# read the JVM Properties
JVMProperties=`/usr/libexec/PlistBuddy -c "print :JavaVM:Properties" ${InfoPlistFile} 2> /dev/null | grep " =" | sed 's/^ */-D/g' | tr '\n' ' ' | sed 's/  */ /g' | sed 's/ = /=/g' | xargs`
	
# read the JVM Options
JVMOptions=`/usr/libexec/PlistBuddy -c "print :JavaVM:VMOptions" ${InfoPlistFile} 2> /dev/null | tr '\n' ' ' | sed -E 's/Array \{ *(.*) *\}/\1/g' | sed 's/  */ /g' | xargs`

# read the JVM Arguments
JVMArguments=`/usr/libexec/PlistBuddy -c "print :JavaVM:Arguments" ${InfoPlistFile} 2> /dev/null | xargs`

#
# find installed Java versions
#################################

# check "/usr/libexec/java_home" tool for location of any installed JDKs
if [ $(/usr/libexec/java_home -F ${JVMVersion:+ -v "$JVMVersion"} 2> /dev/null) ]; then

    # Check for 32-bit and select it if available
    if [ $(/usr/libexec/java_home -F -d32 ${JVMVersion:+ -v "$JVMVersion"} 2> /dev/null) ]; then 
        JVMOptions="$JVMOptions -d32"
        JAVACMD="`/usr/libexec/java_home -d32 ${JVMVersion:+ -v "$JVMVersion"}`/bin/java"

    # fallback: 64 bit
    else
        JAVACMD="`/usr/libexec/java_home ${JVMVersion:+ -v "$JVMVersion"}`/bin/java"
    fi
# fallback: public JRE plugin (Oracle Java)
else
    JAVACMD="/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java"
fi


#
# execute JAVA commandline and do some pre-checks
####################################################
	
# display error message if MainClassName is empty
if [ ${JVMMainClass} == "" ]; then
	# display error message with applescript
	osascript -e "tell application \"System Events\" to display dialog \"ERROR launching ${CFBundleName}!\n\nNo MainClassName specified!\nJava application cannot be started!\" with title \"${CFBundleName}\" buttons {\" OK \"} default button 1 with icon path to resource \"${CFBundleIconFile}\" in bundle (path to me)"
	# exit with error
	exit 1
	
	
# check whether $JAVACMD is executable
elif [ -x "$JAVACMD" ]; then

	# enable drag&drop to the dock icon
	export CFProcessPath="$0"

	# execute Java and set
	#	- classpath
	#	- dock icon
	#	- application name
	#	- JVM properties
	#	- JVM options
	#	- main class
	#	- JVM arguments
	exec "$JAVACMD" $(eval echo \
			-Djava.class.path="${JVMClasspath}" \
			-Xdock:icon="$APP_PACKAGE/Contents/Resources/${CFBundleIconFile}" \
			-Xdock:name="${CFBundleName}" \
			${JVMProperties:+"$JVMProperties" }\
			${JVMOptions:+"$JVMOptions" }\
			"${JVMMainClass}"\
			${JVMArguments:+"$JVMArguments"})
	
	
else

	# display error message with applescript
	osascript -e "tell application \"System Events\" to display dialog \"ERROR launching ${CFBundleName}!\n\nYou need to have JAVA installed on your Mac!\nVisit http://java.com for more information...\" with title \"${CFBundleName}\" buttons {\" OK \"} default button 1 with icon path to resource \"${CFBundleIconFile}\" in bundle (path to me)"
	
	# and open java.com
	open http://java.com
	
	# exit with error
	exit 1
fi