#ivy cached data file for none#mp3spi;1.9.4.1
#Tue Apr 07 07:30:35 EDT 2026
artifact.resolver=cvslib
artifact\:mp3spi\#jar\#jar\#-504164529.exists=true
artifact\:mp3spi\#jar\#jar\#-504164529.is-local=true
artifact\:mp3spi\#jar\#jar\#-504164529.location=/Users/nick/Documents/hermes-wireshare/main/lib/jars/mp3spi-1.9.4.1.jar
artifact\:mp3spi\#jar\#jar\#-504164529.original=artifact\:mp3spi\#jar\#jar\#-504164529
resolver=cvslib
