#ivy cached data file for none#osx/cglib;2.2
#Tue Apr 07 07:30:35 EDT 2026
artifact.resolver=cvslib
artifact\:osx/cglib\#jar\#jar\#-2030717494.exists=true
artifact\:osx/cglib\#jar\#jar\#-2030717494.is-local=true
artifact\:osx/cglib\#jar\#jar\#-2030717494.location=/Users/nick/Documents/hermes-wireshare/main/lib/jars/osx/cglib-2.2.jar
artifact\:osx/cglib\#jar\#jar\#-2030717494.original=artifact\:osx/cglib\#jar\#jar\#-2030717494
resolver=cvslib
