#ivy cached data file for none#windows/jacob;1.15-M1-lw
#Tue Apr 07 07:30:35 EDT 2026
artifact.resolver=cvslib
artifact\:windows/jacob\#jar\#jar\#-1401659989.exists=true
artifact\:windows/jacob\#jar\#jar\#-1401659989.is-local=true
artifact\:windows/jacob\#jar\#jar\#-1401659989.location=/Users/nick/Documents/hermes-wireshare/main/lib/jars/windows/jacob-1.15-M1-lw.jar
artifact\:windows/jacob\#jar\#jar\#-1401659989.original=artifact\:windows/jacob\#jar\#jar\#-1401659989
resolver=cvslib
