#ivy cached data file for org.limewire#mojito;working@local
#Tue Apr 07 07:30:33 EDT 2026
artifact\:ivy\#ivy.original\#xml\#-1816293094.exists=true
artifact\:ivy\#ivy.original\#xml\#-1816293094.is-local=true
artifact\:ivy\#ivy.original\#xml\#-1816293094.location=/Users/nick/Documents/hermes-wireshare/main/.ivy2/local/org.limewire/mojito/ivys/ivy.xml
artifact\:ivy\#ivy.original\#xml\#-1816293094.original=artifact\:ivy\#ivy.original\#xml\#-1816293094
