#ivy cached data file for none#smackx;
#Tue Apr 07 07:30:35 EDT 2026
artifact.resolver=cvslib
artifact\:smackx\#jar\#jar\#1090347205.exists=true
artifact\:smackx\#jar\#jar\#1090347205.is-local=true
artifact\:smackx\#jar\#jar\#1090347205.location=/Users/nick/Documents/hermes-wireshare/main/lib/jars/smackx.jar
artifact\:smackx\#jar\#jar\#1090347205.original=artifact\:smackx\#jar\#jar\#1090347205
resolver=cvslib
