#ivy cached data file for none#AnimatedTransitions;0.11
#Tue Apr 07 07:30:35 EDT 2026
artifact.resolver=cvslib
artifact\:AnimatedTransitions\#jar\#jar\#772174561.exists=true
artifact\:AnimatedTransitions\#jar\#jar\#772174561.is-local=true
artifact\:AnimatedTransitions\#jar\#jar\#772174561.location=/Users/nick/Documents/hermes-wireshare/main/lib/jars/AnimatedTransitions-0.11.jar
artifact\:AnimatedTransitions\#jar\#jar\#772174561.original=artifact\:AnimatedTransitions\#jar\#jar\#772174561
resolver=cvslib
