#ivy cached data file for org.limewire#xmpp-api;working@local
#Tue Apr 07 07:30:33 EDT 2026
artifact\:ivy\#ivy.original\#xml\#-730730442.exists=true
artifact\:ivy\#ivy.original\#xml\#-730730442.is-local=true
artifact\:ivy\#ivy.original\#xml\#-730730442.location=/Users/nick/Documents/hermes-wireshare/main/.ivy2/local/org.limewire/xmpp-api/ivys/ivy.xml
artifact\:ivy\#ivy.original\#xml\#-730730442.original=artifact\:ivy\#ivy.original\#xml\#-730730442
