#ivy cached data file for org.limewire#statistic;working@local
#Tue Apr 07 07:30:33 EDT 2026
artifact\:ivy\#ivy.original\#xml\#1691749858.exists=true
artifact\:ivy\#ivy.original\#xml\#1691749858.is-local=true
artifact\:ivy\#ivy.original\#xml\#1691749858.location=/Users/nick/Documents/hermes-wireshare/main/.ivy2/local/org.limewire/statistic/ivys/ivy.xml
artifact\:ivy\#ivy.original\#xml\#1691749858.original=artifact\:ivy\#ivy.original\#xml\#1691749858
