#ivy cached data file for none#MozillaGlue;1.9
#Tue Apr 07 07:30:35 EDT 2026
artifact.resolver=cvslib
artifact\:MozillaGlue\#jar\#jar\#1522056645.exists=true
artifact\:MozillaGlue\#jar\#jar\#1522056645.is-local=true
artifact\:MozillaGlue\#jar\#jar\#1522056645.location=/Users/nick/Documents/hermes-wireshare/main/lib/jars/MozillaGlue-1.9.jar
artifact\:MozillaGlue\#jar\#jar\#1522056645.original=artifact\:MozillaGlue\#jar\#jar\#1522056645
resolver=cvslib
