#ivy cached data file for none#jna;3.2.4
#Tue Apr 07 07:30:35 EDT 2026
artifact.resolver=cvslib
artifact\:jna\#jar\#jar\#-1167374182.exists=true
artifact\:jna\#jar\#jar\#-1167374182.is-local=true
artifact\:jna\#jar\#jar\#-1167374182.location=/Users/nick/Documents/hermes-wireshare/main/lib/jars/jna-3.2.4.jar
artifact\:jna\#jar\#jar\#-1167374182.original=artifact\:jna\#jar\#jar\#-1167374182
resolver=cvslib
