#ivy cached data file for none#dnsjava;2.0.6
#Tue Apr 07 07:30:35 EDT 2026
artifact.resolver=cvslib
artifact\:dnsjava\#jar\#jar\#1728689303.exists=true
artifact\:dnsjava\#jar\#jar\#1728689303.is-local=true
artifact\:dnsjava\#jar\#jar\#1728689303.location=/Users/nick/Documents/hermes-wireshare/main/lib/jars/dnsjava-2.0.6.jar
artifact\:dnsjava\#jar\#jar\#1728689303.original=artifact\:dnsjava\#jar\#jar\#1728689303
resolver=cvslib
