#ivy cached data file for none#onion-common;
#Tue Apr 07 07:30:35 EDT 2026
artifact.resolver=cvslib
artifact\:onion-common\#jar\#jar\#-234201033.exists=true
artifact\:onion-common\#jar\#jar\#-234201033.is-local=true
artifact\:onion-common\#jar\#jar\#-234201033.location=/Users/nick/Documents/hermes-wireshare/main/lib/jars/onion-common.jar
artifact\:onion-common\#jar\#jar\#-234201033.original=artifact\:onion-common\#jar\#jar\#-234201033
resolver=cvslib
