#ivy cached data file for none#osx/slf4j-jdk14;1.5.8
#Tue Apr 07 07:30:35 EDT 2026
artifact.resolver=cvslib
artifact\:osx/slf4j-jdk14\#jar\#jar\#35885521.exists=true
artifact\:osx/slf4j-jdk14\#jar\#jar\#35885521.is-local=true
artifact\:osx/slf4j-jdk14\#jar\#jar\#35885521.location=/Users/nick/Documents/hermes-wireshare/main/lib/jars/osx/slf4j-jdk14-1.5.8.jar
artifact\:osx/slf4j-jdk14\#jar\#jar\#35885521.original=artifact\:osx/slf4j-jdk14\#jar\#jar\#35885521
resolver=cvslib
