#ivy cached data file for none#AppFramework;
#Tue Apr 07 07:30:35 EDT 2026
artifact.resolver=cvslib
artifact\:AppFramework\#jar\#jar\#1586792385.exists=true
artifact\:AppFramework\#jar\#jar\#1586792385.is-local=true
artifact\:AppFramework\#jar\#jar\#1586792385.location=/Users/nick/Documents/hermes-wireshare/main/lib/jars/AppFramework.jar
artifact\:AppFramework\#jar\#jar\#1586792385.original=artifact\:AppFramework\#jar\#jar\#1586792385
resolver=cvslib
