#ivy cached data file for none#jdic;
#Tue Apr 07 07:30:35 EDT 2026
artifact.resolver=cvslib
artifact\:jdic\#jar\#jar\#1939082550.exists=true
artifact\:jdic\#jar\#jar\#1939082550.is-local=true
artifact\:jdic\#jar\#jar\#1939082550.location=/Users/nick/Documents/hermes-wireshare/main/lib/jars/jdic.jar
artifact\:jdic\#jar\#jar\#1939082550.original=artifact\:jdic\#jar\#jar\#1939082550
resolver=cvslib
