#ivy cached data file for org.limewire#xmpp;working@local
#Tue Apr 07 07:30:34 EDT 2026
artifact\:ivy\#ivy.original\#xml\#1958415300.exists=true
artifact\:ivy\#ivy.original\#xml\#1958415300.is-local=true
artifact\:ivy\#ivy.original\#xml\#1958415300.location=/Users/nick/Documents/hermes-wireshare/main/.ivy2/local/org.limewire/xmpp/ivys/ivy.xml
artifact\:ivy\#ivy.original\#xml\#1958415300.original=artifact\:ivy\#ivy.original\#xml\#1958415300
