#ivy cached data file for org.limewire#core-settings;working@local
#Tue Apr 07 07:30:34 EDT 2026
artifact\:ivy\#ivy.original\#xml\#395431324.exists=true
artifact\:ivy\#ivy.original\#xml\#395431324.is-local=true
artifact\:ivy\#ivy.original\#xml\#395431324.location=/Users/nick/Documents/hermes-wireshare/main/.ivy2/local/org.limewire/core-settings/ivys/ivy.xml
artifact\:ivy\#ivy.original\#xml\#395431324.original=artifact\:ivy\#ivy.original\#xml\#395431324
