#ivy cached data file for none#google-collect;1.0-rc2
#Tue Apr 07 07:30:35 EDT 2026
artifact.resolver=cvslib
artifact\:google-collect\#jar\#jar\#701719447.exists=true
artifact\:google-collect\#jar\#jar\#701719447.is-local=true
artifact\:google-collect\#jar\#jar\#701719447.location=/Users/nick/Documents/hermes-wireshare/main/lib/jars/google-collect-1.0-rc2.jar
artifact\:google-collect\#jar\#jar\#701719447.original=artifact\:google-collect\#jar\#jar\#701719447
resolver=cvslib
