#ivy cached data file for org.limewire#swingui;working@local
#Tue Apr 07 07:30:35 EDT 2026
artifact\:ivy\#ivy.original\#xml\#-846315562.exists=true
artifact\:ivy\#ivy.original\#xml\#-846315562.is-local=true
artifact\:ivy\#ivy.original\#xml\#-846315562.location=/Users/nick/Documents/hermes-wireshare/main/.ivy2/local/org.limewire/swingui/ivys/ivy.xml
artifact\:ivy\#ivy.original\#xml\#-846315562.original=artifact\:ivy\#ivy.original\#xml\#-846315562
