#ivy cached data file for none#jmdns;
#Tue Apr 07 07:30:35 EDT 2026
artifact.resolver=cvslib
artifact\:jmdns\#jar\#jar\#-481960724.exists=true
artifact\:jmdns\#jar\#jar\#-481960724.is-local=true
artifact\:jmdns\#jar\#jar\#-481960724.location=/Users/nick/Documents/hermes-wireshare/main/lib/jars/jmdns.jar
artifact\:jmdns\#jar\#jar\#-481960724.original=artifact\:jmdns\#jar\#jar\#-481960724
resolver=cvslib
