#ivy cached data file for none#jaudiotagger;1.0.9.1
#Tue Apr 07 07:30:35 EDT 2026
artifact.resolver=cvslib
artifact\:jaudiotagger\#jar\#jar\#1730426809.exists=true
artifact\:jaudiotagger\#jar\#jar\#1730426809.is-local=true
artifact\:jaudiotagger\#jar\#jar\#1730426809.location=/Users/nick/Documents/hermes-wireshare/main/lib/jars/jaudiotagger-1.0.9.1.jar
artifact\:jaudiotagger\#jar\#jar\#1730426809.original=artifact\:jaudiotagger\#jar\#jar\#1730426809
resolver=cvslib
