#ivy cached data file for none#jogg;
#Tue Apr 07 07:30:35 EDT 2026
artifact.resolver=cvslib
artifact\:jogg\#jar\#jar\#1972923897.exists=true
artifact\:jogg\#jar\#jar\#1972923897.is-local=true
artifact\:jogg\#jar\#jar\#1972923897.location=/Users/nick/Documents/hermes-wireshare/main/lib/jars/jogg.jar
artifact\:jogg\#jar\#jar\#1972923897.original=artifact\:jogg\#jar\#jar\#1972923897
resolver=cvslib
