#ivy cached data file for none#daap;
#Tue Apr 07 07:30:35 EDT 2026
artifact.resolver=cvslib
artifact\:daap\#jar\#jar\#1353662334.exists=true
artifact\:daap\#jar\#jar\#1353662334.is-local=true
artifact\:daap\#jar\#jar\#1353662334.location=/Users/nick/Documents/hermes-wireshare/main/lib/jars/daap.jar
artifact\:daap\#jar\#jar\#1353662334.original=artifact\:daap\#jar\#jar\#1353662334
resolver=cvslib
