#ivy cached data file for none#commons-codec;1.3
#Tue Apr 07 07:30:35 EDT 2026
artifact.resolver=cvslib
artifact\:commons-codec\#jar\#jar\#1494520411.exists=true
artifact\:commons-codec\#jar\#jar\#1494520411.is-local=true
artifact\:commons-codec\#jar\#jar\#1494520411.location=/Users/nick/Documents/hermes-wireshare/main/lib/jars/commons-codec-1.3.jar
artifact\:commons-codec\#jar\#jar\#1494520411.original=artifact\:commons-codec\#jar\#jar\#1494520411
resolver=cvslib
