#ivy cached data file for org.limewire#io;working@local
#Tue Apr 07 07:30:32 EDT 2026
artifact\:ivy\#ivy.original\#xml\#-554408354.exists=true
artifact\:ivy\#ivy.original\#xml\#-554408354.is-local=true
artifact\:ivy\#ivy.original\#xml\#-554408354.location=/Users/nick/Documents/hermes-wireshare/main/.ivy2/local/org.limewire/io/ivys/ivy.xml
artifact\:ivy\#ivy.original\#xml\#-554408354.original=artifact\:ivy\#ivy.original\#xml\#-554408354
