#ivy cached data file for org.limewire#net;working@local
#Tue Apr 07 07:30:32 EDT 2026
artifact\:ivy\#ivy.original\#xml\#-359065004.exists=true
artifact\:ivy\#ivy.original\#xml\#-359065004.is-local=true
artifact\:ivy\#ivy.original\#xml\#-359065004.location=/Users/nick/Documents/hermes-wireshare/main/.ivy2/local/org.limewire/net/ivys/ivy.xml
artifact\:ivy\#ivy.original\#xml\#-359065004.original=artifact\:ivy\#ivy.original\#xml\#-359065004
