#ivy cached data file for none#MozillaInterfaces;1.9
#Tue Apr 07 07:30:35 EDT 2026
artifact.resolver=cvslib
artifact\:MozillaInterfaces\#jar\#jar\#-358187260.exists=true
artifact\:MozillaInterfaces\#jar\#jar\#-358187260.is-local=true
artifact\:MozillaInterfaces\#jar\#jar\#-358187260.location=/Users/nick/Documents/hermes-wireshare/main/lib/jars/MozillaInterfaces-1.9.jar
artifact\:MozillaInterfaces\#jar\#jar\#-358187260.original=artifact\:MozillaInterfaces\#jar\#jar\#-358187260
resolver=cvslib
