#ivy cached data file for none#miglayout;3.7-swing
#Tue Apr 07 07:30:35 EDT 2026
artifact.resolver=cvslib
artifact\:miglayout\#jar\#jar\#-1240881646.exists=true
artifact\:miglayout\#jar\#jar\#-1240881646.is-local=true
artifact\:miglayout\#jar\#jar\#-1240881646.location=/Users/nick/Documents/hermes-wireshare/main/lib/jars/miglayout-3.7-swing.jar
artifact\:miglayout\#jar\#jar\#-1240881646.original=artifact\:miglayout\#jar\#jar\#-1240881646
resolver=cvslib
