#ivy cached data file for none#messages;
#Tue Apr 07 07:30:35 EDT 2026
artifact.resolver=cvslib
artifact\:messages\#jar\#jar\#-1378146018.exists=true
artifact\:messages\#jar\#jar\#-1378146018.is-local=true
artifact\:messages\#jar\#jar\#-1378146018.location=/Users/nick/Documents/hermes-wireshare/main/lib/jars/messages.jar
artifact\:messages\#jar\#jar\#-1378146018.original=artifact\:messages\#jar\#jar\#-1378146018
resolver=cvslib
