#ivy cached data file for none#gettext-commons;
#Tue Apr 07 07:30:35 EDT 2026
artifact.resolver=cvslib
artifact\:gettext-commons\#jar\#jar\#-263265228.exists=true
artifact\:gettext-commons\#jar\#jar\#-263265228.is-local=true
artifact\:gettext-commons\#jar\#jar\#-263265228.location=/Users/nick/Documents/hermes-wireshare/main/lib/jars/gettext-commons.jar
artifact\:gettext-commons\#jar\#jar\#-263265228.original=artifact\:gettext-commons\#jar\#jar\#-263265228
resolver=cvslib
