#ivy cached data file for none#htmlcleaner;2.1
#Tue Apr 07 07:30:35 EDT 2026
artifact.resolver=cvslib
artifact\:htmlcleaner\#jar\#jar\#-973788804.exists=true
artifact\:htmlcleaner\#jar\#jar\#-973788804.is-local=true
artifact\:htmlcleaner\#jar\#jar\#-973788804.location=/Users/nick/Documents/hermes-wireshare/main/lib/jars/htmlcleaner-2.1.jar
artifact\:htmlcleaner\#jar\#jar\#-973788804.original=artifact\:htmlcleaner\#jar\#jar\#-973788804
resolver=cvslib
