#ivy cached data file for none#mozdom4java;
#Tue Apr 07 07:30:35 EDT 2026
artifact.resolver=cvslib
artifact\:mozdom4java\#jar\#jar\#-816533122.exists=true
artifact\:mozdom4java\#jar\#jar\#-816533122.is-local=true
artifact\:mozdom4java\#jar\#jar\#-816533122.location=/Users/nick/Documents/hermes-wireshare/main/lib/jars/mozdom4java.jar
artifact\:mozdom4java\#jar\#jar\#-816533122.original=artifact\:mozdom4java\#jar\#jar\#-816533122
resolver=cvslib
