#ivy cached data file for none#tritonus;
#Tue Apr 07 07:30:35 EDT 2026
artifact.resolver=cvslib
artifact\:tritonus\#jar\#jar\#-1140234996.exists=true
artifact\:tritonus\#jar\#jar\#-1140234996.is-local=true
artifact\:tritonus\#jar\#jar\#-1140234996.location=/Users/nick/Documents/hermes-wireshare/main/lib/jars/tritonus.jar
artifact\:tritonus\#jar\#jar\#-1140234996.original=artifact\:tritonus\#jar\#jar\#-1140234996
resolver=cvslib
