#ivy cached data file for org.limewire#setting;working@local
#Tue Apr 07 07:30:34 EDT 2026
artifact\:ivy\#ivy.original\#xml\#1233309666.exists=true
artifact\:ivy\#ivy.original\#xml\#1233309666.is-local=true
artifact\:ivy\#ivy.original\#xml\#1233309666.location=/Users/nick/Documents/hermes-wireshare/main/.ivy2/local/org.limewire/setting/ivys/ivy.xml
artifact\:ivy\#ivy.original\#xml\#1233309666.original=artifact\:ivy\#ivy.original\#xml\#1233309666
