#ivy cached data file for none#icu4j;
#Tue Apr 07 07:30:35 EDT 2026
artifact.resolver=cvslib
artifact\:icu4j\#jar\#jar\#-72007747.exists=true
artifact\:icu4j\#jar\#jar\#-72007747.is-local=true
artifact\:icu4j\#jar\#jar\#-72007747.location=/Users/nick/Documents/hermes-wireshare/main/lib/jars/icu4j.jar
artifact\:icu4j\#jar\#jar\#-72007747.original=artifact\:icu4j\#jar\#jar\#-72007747
resolver=cvslib
