#ivy cached data file for org.limewire#security;working@local
#Tue Apr 07 07:30:32 EDT 2026
artifact\:ivy\#ivy.original\#xml\#-1324931518.exists=true
artifact\:ivy\#ivy.original\#xml\#-1324931518.is-local=true
artifact\:ivy\#ivy.original\#xml\#-1324931518.location=/Users/nick/Documents/hermes-wireshare/main/.ivy2/local/org.limewire/security/ivys/ivy.xml
artifact\:ivy\#ivy.original\#xml\#-1324931518.original=artifact\:ivy\#ivy.original\#xml\#-1324931518
