#ivy cached data file for org.limewire#nio;working@local
#Tue Apr 07 07:30:32 EDT 2026
artifact\:ivy\#ivy.original\#xml\#-358844854.exists=true
artifact\:ivy\#ivy.original\#xml\#-358844854.is-local=true
artifact\:ivy\#ivy.original\#xml\#-358844854.location=/Users/nick/Documents/hermes-wireshare/main/.ivy2/local/org.limewire/nio/ivys/ivy.xml
artifact\:ivy\#ivy.original\#xml\#-358844854.original=artifact\:ivy\#ivy.original\#xml\#-358844854
