#ivy cached data file for none#clink;
#Tue Apr 07 07:30:35 EDT 2026
artifact.resolver=cvslib
artifact\:clink\#jar\#jar\#102721377.exists=true
artifact\:clink\#jar\#jar\#102721377.is-local=true
artifact\:clink\#jar\#jar\#102721377.location=/Users/nick/Documents/hermes-wireshare/main/lib/jars/clink.jar
artifact\:clink\#jar\#jar\#102721377.original=artifact\:clink\#jar\#jar\#102721377
resolver=cvslib
