#ivy cached data file for org.limewire#mojito-ui;working@local
#Tue Apr 07 07:30:35 EDT 2026
artifact\:ivy\#ivy.original\#xml\#1394666916.exists=true
artifact\:ivy\#ivy.original\#xml\#1394666916.is-local=true
artifact\:ivy\#ivy.original\#xml\#1394666916.location=/Users/nick/Documents/hermes-wireshare/main/.ivy2/local/org.limewire/mojito-ui/ivys/ivy.xml
artifact\:ivy\#ivy.original\#xml\#1394666916.original=artifact\:ivy\#ivy.original\#xml\#1394666916
